### PR TITLE
Files js & css

### PR DESCRIPTION
**Pull request by ebarquero85**
Sometimes files are not in the root directory of the domain eg: 

`www.mydomain.com/larveltest/js/fullcalendar.js `

This change solves it.

### CODE REVIEW

**Comment by Edofre** [comment]
Thanks for the PR! Could you also add this update in the tests? I think it should pass if you would also wrap the urls in tests/Integration/FullcalendarTest.php.

**Comment by ebarquero85** [comment]
I just made what you suggested

**Comment by Edofre** [comment]
Thank you!

**Comment by ebarquero85** [comment]
your welcome!

**Pull request merged**
